on:
  push:
    branches:
      - '*'

jobs:
  cleanUp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        matrix:
          site: [SITE1, SITE2]
          subpath: [ sites/all/modules/ereol, sites/all/modules/breol]
    steps:
      - name: Set env
        run: echo ::set-env name=SITE_PATH::APP_TEST_${{ matrix.site }}
 
      - name: Test
        run: echo ${{ matrix.subpath }}
