on:
  push:
    branches:
      - '*'

jobs:
  cleanUp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [SITE1, SITE2]
    steps:
      - name: Set env
        run: echo ::set-env name=SITE_PATH::APP_TEST_${{ matrix.site }}
 
      - name: Test
        run: echo ${{ secrets[env.SITE_PATH] }}
