on:
  push:
    branches:
      - '*'

jobs:
  cleanUp:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        site: [SITE1, SITE2]
    steps:
      - name: Set env
        run: echo ::set-env name=SITE_PATH::APP_TEST_${{ martix.site }}
      - name: Test (${{ matrix.site }})
        run: echo ${{ secrets[$SITE_PATH] }}
