on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Access secrets
        run: echo ${{ secrets.SUPERTEST }}
        
      - name: Test
        run: echo "test"
