on:
  push:
    branches-ignore:
      - '*'
    tags: 
      - '*'

env:
  ORG_NAME: danskernesdigitalebibliotek
  APP_VERSION: ${{ github.event.ref }}
  NAMESPACE: cover-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the major version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the major version
        id: get_version
        run: echo ::set-output name=MAJOR::${steps.get_version.outputs.VERSION:0:1}


      - name: Echo version
        run: echo ${{ env.APP_VERSION }}

      - name: Echo version2
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Echo version2
        run: echo ${{ steps.get_version.outputs.MAJOR }}
