on:
  push:
    tags:

env:
  ORG_NAME: danskernesdigitalebibliotek
  APP_VERSION: ${{ github.event.ref }}
  NAMESPACE: cover-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Echo version
        run: echo ${{ env.APP_VERSION }}